name: Build Packages Install Packages on ConsoleApp

on:
  push:
    branches: [ juzuluag/pkg_with_old_code_branch ]
  pull_request:
    types: [labeled]
    branches: [ dev, main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'samples/lib-integration/ConsoleApp/**'

env:
  PREFIX: "0.0.1"
  DOTNET_SOLUTION: "./src/CarbonAwareSDK.sln"
  OUTPUT_DIR: "packages"
  CONSOLE_APP: "./samples/lib-integration/ConsoleApp/ConsoleApp.csproj"
  PKG_SCRIPTS_DIR: "scripts/package"

jobs:
  dotnet-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Make package dir
        run: mkdir -p ${{ env.OUTPUT_DIR }}

      - name: Run create packages
        run: ./create_packages ${{ env.OUTPUT_DIR }}
        working-directory: ${{ env.PKG_SCRIPTS_DIR }}

      - name: Restore current packages for ConsoleApp
        run: dotnet restore ${{ env.CONSOLE_APP }}

      - name: Add packages to ConsoleApp
        run: ./add_packages ${{ env.CONSOLE_APP}} ${{ env.OUTPUT_DIR }}
        working-directory: ${{ env.PKG_SCRIPTS_DIR }}

      - name: Restore packages after Add to ConsoleAppSample
        run: dotnet restore ${{ env.CONSOLE_APP }}

      - name: Build ConsoleApp
        run: dotnet build ${{ env.CONSOLE_APP }}

      - name: Run ConsoleApp
        run: dotnet run --project ${{ env.CONSOLE_APP }}
